#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("xamTest.Resource", IsApplication=true)]

namespace xamTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int nav_items = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int eyeicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icmenublack24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icrefreshblack24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icsaveblack24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int menu_button = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int refresh_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int round_button = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000f
			public const int bottomDecreaseButton = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int bottomIncreaseButton = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int bottomLifeCounter = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int drawer_layout = 2131165200;
			
			// aapt resource value: 0x7f070016
			public const int eyeIcon = 2131165206;
			
			// aapt resource value: 0x7f070007
			public const int gameTimer = 2131165191;
			
			// aapt resource value: 0x7f07001a
			public const int left_drawer = 2131165210;
			
			// aapt resource value: 0x7f070008
			public const int lifeCounterIcons = 2131165192;
			
			// aapt resource value: 0x7f070018
			public const int lifeCounterLayout = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int lifeCounterMenuButton = 2131165209;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout1 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int menuBar = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int menuHeader = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int menuIcon = 2131165204;
			
			// aapt resource value: 0x7f07001b
			public const int menuViewPager = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int navMenu = 2131165212;
			
			// aapt resource value: 0x7f070009
			public const int refreshTimerButton = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int relativeLayout2 = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int relativeLayout3 = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int relativeLayout4 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int relativeLayout5 = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int relativeLayout6 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int relativeLayout7 = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int saveGameButton = 2131165194;
			
			// aapt resource value: 0x7f070017
			public const int space2 = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int textView1 = 2131165205;
			
			// aapt resource value: 0x7f070003
			public const int topDecreaseButton = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int topIncreaseButton = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int topLifeCounter = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int LifeCounter = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Menu = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int navMenu = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int preference_file = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
